name: // At the end of every day
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Gitleaks check
        run: |
          docker pull zricethezav/gitleaks:v8.18.4
          docker run --rm -v ${{ github.workspace }}:/work -work zricethezav/gitleaks:v8.18.4 detect --source="." --config="/work/gitleaks.toml" --verbose --no-git